dist: trusty
sudo: required
language: clojure

cache:
  directories:
    - $HOME/.npm
    - $TRAVIS_BUILD_DIR/.cache
    - $TRAVIS_BUILD_DIR/node_modules

before_install:
  - sudo apt-get install -y leiningen
  - npm install lumo-cljs@1.9.0-alpha -g

install:
  - jdk_switcher use openjdk8

script: lein do check, eastwood, test-all, tach lumo, test-readme
