dist: trusty
sudo: required
language: clojure

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
    - $TRAVIS_BUILD_DIR/.cache
    - $TRAVIS_BUILD_DIR/node_modules

before_install:
  - npm install lumo-cljs@1.8.0 -g

install:
  - jdk_switcher use openjdk8

script: lein do check, eastwood, test-all, tach lumo, test-readme
