version: 2
jobs:
  build:
    working_directory: ~/honeysql
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.0.442
#    environment:
#      JVM_OPTS:  -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: honeysql-{{ checksum "deps.edn" }}
      - run:
          name: Install Node
          command: sudo apt-get install -y nodejs
      - run:
          name: Add node symlink
          command: sudo ln -s /usr/bin/js /usr/bin/node
      - run:
          name: Download Dependencies
          command: clojure -R:test:runner:cljs-runner:eastwood:readme -Spath && clojure -A:1.7 -Spath && clojure -A:1.8 -Spath && clojure -A:1.9 -Spath
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
            - ~/node_modules
          key: honeysql-{{ checksum "deps.edn" }}
      - run:
          name: Run all the tests
          command: sh run-tests.sh all
